import jsPDF from "jspdf";
import { useState } from "react";

const PDFExport = ({ resumeData, gapData, planData, targetRole }) => {
  const [isExporting, setIsExporting] = useState(false);

  const exportPDF = async () => {
    setIsExporting(true);

    const pdf = new jsPDF("p", "mm", "a4");
    const pageWidth = pdf.internal.pageSize.getWidth();
    let y = 20;

    // ─── Helper Functions ───────────────────────
    const addTitle = (text, size = 16) => {
      pdf.setFontSize(size);
      pdf.setTextColor(59, 130, 246);
      pdf.text(text, 20, y);
      y += size * 0.6;
    };

    const addText = (text, size = 11, color = [200, 200, 200]) => {
      pdf.setFontSize(size);
      pdf.setTextColor(...color);
      const lines = pdf.splitTextToSize(text, pageWidth - 40);
      pdf.text(lines, 20, y);
      y += lines.length * size * 0.5 + 3;
    };

    const addLine = () => {
      pdf.setDrawColor(55, 65, 81);
      pdf.line(20, y, pageWidth - 20, y);
      y += 6;
    };

    const checkPage = (needed = 20) => {
      if (y + needed > 270) {
        pdf.addPage();
        y = 20;
      }
    };

    // ─── Set Dark Background ────────────────────
    pdf.setFillColor(17, 24, 39);
    pdf.rect(0, 0, pageWidth, 297, "F");

    // ─── Header ─────────────────────────────────
    pdf.setFillColor(37, 99, 235);
    pdf.rect(0, 0, pageWidth, 35, "F");
    pdf.setFontSize(22);
    pdf.setTextColor(255, 255, 255);
    pdf.text("CareerForge AI", 20, 15);
    pdf.setFontSize(11);
    pdf.setTextColor(191, 219, 254);
    pdf.text("Career Analysis Report", 20, 25);
    pdf.setFontSize(10);
    pdf.setTextColor(147, 197, 253);
    pdf.text(`Target Role: ${targetRole}`, pageWidth - 80, 20);
    pdf.text(`Generated: ${new Date().toLocaleDateString()}`, pageWidth - 80, 28);
    y = 45;

    // ─── Candidate Info ──────────────────────────
    addTitle("👤 Candidate Profile", 14);
    y += 2;
    addText(`Name: ${resumeData?.name || "N/A"}`, 11, [255, 255, 255]);
    addText(`Education: ${resumeData?.education || "N/A"}`, 11, [200, 200, 200]);
    addText(`Experience: ${resumeData?.experience_years || 0} years`, 11, [200, 200, 200]);
    addText(`Resume Score: ${resumeData?.overall_score}/10`, 11, [200, 200, 200]);
    addLine();

    // ─── Skills ──────────────────────────────────
    checkPage(30);
    addTitle("✅ Strong Skills", 14);
    y += 2;
    const skills = resumeData?.skills || [];
    const skillsText = skills.join(" • ");
    addText(skillsText, 10, [134, 239, 172]);
    addLine();

    // ─── Gap Analysis ────────────────────────────
    checkPage(30);
    addTitle("📊 Gap Analysis", 14);
    y += 2;
    addText(`Job Match: ${gapData?.overall_match_percentage}%`, 11, [255, 255, 255]);
    y += 3;

    addText("Missing Critical Skills:", 11, [252, 165, 165]);
    gapData?.missing_critical_skills?.forEach((item) => {
      checkPage(15);
      addText(`  • ${item.skill} [${item.importance}] — ${item.reason || ""}`, 10, [200, 200, 200]);
    });
    y += 3;

    addText("Summary:", 11, [255, 255, 255]);
    addText(gapData?.summary || "", 10, [200, 200, 200]);
    addLine();

    // ─── Immediate Actions ───────────────────────
    checkPage(30);
    addTitle("⚡ Immediate Actions", 14);
    y += 2;
    gapData?.immediate_actions?.forEach((action, i) => {
      checkPage(12);
      addText(`${i + 1}. ${action}`, 10, [200, 200, 200]);
    });
    addLine();

    // ─── 30 Day Plan ─────────────────────────────
    checkPage(30);
    addTitle("🗺️ 30-Day Action Plan", 14);
    y += 2;

    planData?.weekly_plans?.forEach((week) => {
      checkPage(25);
      pdf.setFontSize(12);
      pdf.setTextColor(96, 165, 250);
      pdf.text(`Week ${week.week} — ${week.focus}`, 20, y);
      y += 7;
      pdf.setFontSize(10);
      pdf.setTextColor(134, 239, 172);
      pdf.text(`Goal: ${week.week_goal}`, 25, y);
      y += 6;

      week.days?.slice(0, 3).forEach((day) => {
        checkPage(12);
        addText(`  Day ${day.day}: ${day.task} (${day.hours}h - ${day.type})`, 9, [200, 200, 200]);
      });
      y += 3;
    });

    addLine();

    // ─── Recommended Projects ────────────────────
    checkPage(30);
    addTitle("🛠️ Recommended Projects", 14);
    y += 2;
    planData?.recommended_projects?.forEach((project) => {
      checkPage(20);
      pdf.setFontSize(11);
      pdf.setTextColor(216, 180, 254);
      pdf.text(`• ${project.name} [${project.difficulty}]`, 20, y);
      y += 6;
      addText(`  ${project.description}`, 9, [200, 200, 200]);
    });

    // ─── Footer ──────────────────────────────────
    pdf.setFillColor(17, 24, 39);
    pdf.setFontSize(9);
    pdf.setTextColor(100, 116, 139);
    pdf.text("Generated by CareerForge AI — Multi-Agent Career Coach", 20, 290);
    pdf.text("Powered by Groq + Llama 3.3 + CrewAI", pageWidth - 80, 290);

    // ─── Save ────────────────────────────────────
    pdf.save(`CareerForge_${resumeData?.name || "Report"}_${targetRole}.pdf`);
    setIsExporting(false);
  };

  return (
    <button
      onClick={exportPDF}
      disabled={isExporting}
      className={`flex items-center gap-2 px-5 py-2.5 rounded-xl font-medium text-sm transition-all ${
        isExporting
          ? "bg-gray-700 text-gray-400 cursor-not-allowed"
          : "bg-gradient-to-r from-blue-600 to-purple-600 hover:from-blue-500 hover:to-purple-500 text-white shadow-lg hover:shadow-blue-500/25"
      }`}
    >
      {isExporting ? (
        <>⏳ Generating PDF...</>
      ) : (
        <>📄 Export PDF Report</>
      )}
    </button>
  );
};

export default PDFExport;